sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - EXTRA_TOOL=
  - EXTRA_TOOL=riemann-aws
  - EXTRA_TOOL=riemann-chronos
  - EXTRA_TOOL=riemann-docker
  - EXTRA_TOOL=riemann-elasticsearch
  - EXTRA_TOOL=riemann-marathon
  - EXTRA_TOOL=riemann-mesos
  - EXTRA_TOOL=riemann-munin
  - EXTRA_TOOL=riemann-rabbitmq
  - EXTRA_TOOL=riemann-riak

before_script:
  - docker version

script:
  - .docker/publish.sh

branches:
  only:
    - master
